### ISSUE TITLE
`rules list` command should support json or yaml output

### ISSUE THREAD

**Issue by jutley** [grafana/cortextool#16]
I'd like to be able to list rules in Cortex, then programatically process them. The output of `rules list` is great for the human eye, but needlessly difficult to program around.

We should add an `-o, --output` flag to support YAML output. JSON output would also be appreciated, though plenty of client tools can make this conversion as necessary.

**Comment by jtlisi** [comment]
Have you tried the `rules print` command? It prints the rules in yaml format.

**Comment by jutley** [comment]
`rules print` works for this. Thank you.
