### ISSUE TITLE
`rules print` should have the option to disable color

### ISSUE THREAD

**Issue by jutley** [grafana/cortextool#17]
Many tools do not handle shell colors very well. In my case, I am trying to parse the YAML output using https://github.com/kislyuk/yq, but it fails due to the colorized input. As a workaround, I have to pipe the output through `sed -e $'s/\x1b\[[0-9;]*m//g'`, which frankly I barely understand.

**Comment by jtlisi** [comment]
#25 allows the option to disable color on rule and alert commands
