### ISSUE TITLE
HTTP requests are not URL encoding parameters

### ISSUE THREAD

**Issue by jutley** [grafana/cortextool#22]
I tried to delete a rule group that includes a `%` in the name. I got an error with the following reasoning:

```
invalid URL escape "% n"
```

Command line inputs need to be sanitized before being used in a URL.

**Comment by jutley** [comment]
Also, I'm finding that any group with a `/` in the name cannot be deleted, even with URL encoding.

**Comment by jtlisi** [comment]
#24 resolves this issue
