### ISSUE TITLE
rules list command returns generic 404 when no rules are configured

### ISSUE THREAD

**Issue by nlowe** [grafana/cortextool#8]
Running `cortextool rules list` when no rules are configured returns the following error message

```bash
$ cortextool rules list
time="2019-12-17T12:49:29-05:00" level=fatal msg="unable to read rules from cortex, requested resource not found"
```

This initially led me to believe there was an issue with my `CORTEX_ADDRESS` value. Should it return an empty list / fail silently instead?

**Comment by jtlisi** [comment]
With #10 this issue has been resolved
