### ISSUE TITLE
alertmanager get command returns generic 404 when no custom configuration has been provided

### ISSUE THREAD

**Issue by nlowe** [grafana/cortextool#9]
Running `cortextool alertmanager get` when no rules are configured returns the following error message

```bash
$ cortextool alertmanager get
cortextool.exe: error: requested resource not found, try --help
```

This initially led me to believe there was an issue with my `CORTEX_ADDRESS` value. Should it return an empty list / fail silently instead?

**Comment by jtlisi** [comment]
#10 should have resolved this issue
